version: '2'

services:
    zsh_for_beginners:
        build: ./
        volumes:
            - ./chroot:/home/zsh:ro
            - ./share/xinetd:/etc/xinetd.d/zsh:ro
            - ./share/run.sh:/run.sh:ro
            - ./share/flag:/flag:ro
            - ./tmp:/tmp:rw
        tmpfs: /home/zsh/tmp
        ports:
            - "10206:4869"
        expose:
            - "4869"
        cap_add:
            - SYS_CHROOT

